import Head from 'next/head'
import { Inter } from 'next/font/google'
import CurrencyExchange from '@/components/currencyExchange/CurrencyExchange'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ currenciesList, error }) {

  return (
    <>
      <Head>
        <title>Money Exchange</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {
          error ? <p>Cannot retrieve currencies list</p> : null
        }

        {
          currenciesList ? <CurrencyExchange currenciesList={currenciesList} /> : null
        }
      </main>
    </>
  )
};

export async function getStaticProps() {
  const url = 'https://currency-exchange.p.rapidapi.com/listquotes';
  const options = {
    method: 'GET',
    headers: {
      'X-RapidAPI-Key': '9af8210d71msh0adc58de1e15513p12c61ajsn6b967a6e4108',
      'X-RapidAPI-Host': 'currency-exchange.p.rapidapi.com'
    }
  };

  try {
    const response = await fetch(url, options);
    const result = await response.json();
    return {
      props: {
        currenciesList: result
      }
    }
  } catch (error) {
    return {
      props: {
        error: true
      }
    };
  }
}