import Head from "next/head";
import CurrencyExchange from "@/components/currencyExchange/CurrencyExchange";
import { useDispatch } from "react-redux";
import { setCurrenciesList } from "@/store/currencySlice";
import { useRouter } from "next/router";

export default function Home({ currenciesList, error }) {
  const dispatch = useDispatch();
  const router = useRouter();

  if (currenciesList?.length) {
    dispatch(setCurrenciesList(currenciesList));
  }

  return (
    <>
      <Head>
        <title>Money Exchange</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {error ? (
          <div>
            <p>Something went wrong, please try again later</p>
            <button
              onClick={() => {
                router.reload();
              }}
            >
              Reload
            </button>
          </div>
        ) : null}
        {currenciesList ? <CurrencyExchange /> : null}
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const url = "https://currency-exchange.p.rapidapi.com/listquotes";
  const options = {
    method: "GET",
    headers: {
      "X-RapidAPI-Key": "9af8210d71msh0adc58de1e15513p12c61ajsn6b967a6e4108",
      "X-RapidAPI-Host": "currency-exchange.p.rapidapi.com",
    },
  };

  try {
    const response = await fetch(url, options);
    const result = await response.json();
    return {
      props: {
        currenciesList: result,
      },
    };
  } catch (error) {
    return {
      props: {
        error: true,
      },
    };
  }
}
